Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/mantic64"
    config.vm.network "private_network", type: "static", ip: "192.168.56.8"
    config.vm.hostname = "minikube"
    
    # Set VM specifications
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048" # 2GB RAM
      vb.cpus = 2 # 2 CPUs
    end
  
    # Define VM provisioning
    config.vm.provision "shell", inline: <<-SHELL
      # Update the package lists
      sudo apt-get update
  
      # Install required packages
      sudo apt-get install -y iptables conntrack crictl apt-transport-https ca-certificates curl software-properties-common selinux-utils
      sudo apt install -y conntrack
      # install docker
      curl -fsSL https://get.docker.com -o get-docker.sh
      sh get-docker.sh
      sudo usermod -aG docker vagrant
      sudo systemctl enable docker
      sudo systemctl start docker
      #install docker compose
      sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
      echo "Docker installation completed."

      # Set SELinux to permissive mode
      sudo setenforce 0
      sudo sed -i 's/^SELINUX=.*/SELINUX=permissive/' /etc/selinux/config
  
      # Ensure cgroups v1 is used (v2 is not yet supported by Kubernetes)
      sudo sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash cgroup_enable=memory cgroup_memory=1 rd.pam=1 systemd.unified_cgroup_hierarchy=0"/' /etc/default/grub
      sudo update-grub
  
      # Install containerd and CNI plugins (for cri-o or other container runtimes)
      sudo apt-get install -y containerd
      sudo mkdir -p /etc/containerd
      containerd config default > /etc/containerd/config.toml
      sudo systemctl restart containerd
      sudo apt-get install -y apt-transport-https
      # Install kubectl
      curl -LO https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/local/bin/kubectl
      kubectl version --client  #display kubectl installed version
      # Install Minikube
      echo "Installing Minikube..."
      curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      sudo install minikube-linux-amd64 /usr/local/bin/minikube
      minikube start --driver=none --kubernetes-version=1.22.0 --extra-config kubeadm.ignore-preflight-errors=SystemVerification #Start Minikube
      #kubectl config use-context minikube #setup Minikube context
      minikube config set driver docker
      echo "Minikube installation complete."
      minikube version  # Verify Minikube installation
    SHELL
end  